"""
NDX (index) file reader for pySuAVE.

NDX files contain atom indices used to select specific atoms for analysis.
Format: Simple text file with one integer per line.

Fortran equivalent: abre_ndx subroutine in funcproc.f90
"""

from pathlib import Path
from typing import List
import numpy as np
import numpy.typing as npt

from pysuave.core.constants import MAX_INDEX


def read_ndx(filepath: str | Path) -> npt.NDArray[np.int32]:
    """
    Read atom indices from an NDX file.
    
    Args:
        filepath: Path to the NDX file
        
    Returns:
        Array of atom indices (0-indexed in Python, unlike 1-indexed Fortran)
        
    Raises:
        FileNotFoundError: If the file doesn't exist
        ValueError: If the file contains invalid data
        
    Example:
        >>> indices = read_ndx("membrane.ndx")
        >>> print(f"Read {len(indices)} atom indices")
    """
    filepath = Path(filepath)
    
    if not filepath.exists():
        raise FileNotFoundError(f"Unable to open file {filepath}")
    
    indices: List[int] = []
    
    try:
        with open(filepath, 'r') as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                
                # Skip empty lines and comments
                if not line or line.startswith('#') or line.startswith('['):
                    continue
                
                # Try to parse integers from the line (can be multiple per line)
                try:
                    values = [int(x) for x in line.split()]
                    indices.extend(values)
                except ValueError as e:
                    raise ValueError(
                        f"Invalid data in {filepath} at line {line_num}: {line}"
                    ) from e
                    
    except IOError as e:
        raise IOError(f"Problem reading {filepath}") from e
    
    if not indices:
        raise ValueError(f"No indices found in {filepath}")
    
    if len(indices) > MAX_INDEX:
        raise ValueError(
            f"Too many indices ({len(indices)}) in {filepath}. "
            f"Maximum allowed: {MAX_INDEX}"
        )
    
    # Convert to 0-indexed (Fortran uses 1-indexed)
    # Assuming input file has 1-indexed atoms
    indices_array = np.array(indices, dtype=np.int32) - 1
    
    print(f"\n{filepath.name} input file is OK")
    print(f"Read {len(indices_array)} atom indices\n")
    
    return indices_array


def write_ndx(filepath: str | Path, indices: npt.NDArray[np.int32], 
              title: str = "Index file generated by pySuAVE") -> None:
    """
    Write atom indices to an NDX file.
    
    Args:
        filepath: Output file path
        indices: Array of atom indices (0-indexed)
        title: Title/comment for the file
    """
    filepath = Path(filepath)
    
    # Convert to 1-indexed for output (Fortran/GROMACS convention)
    indices_1indexed = indices + 1
    
    with open(filepath, 'w') as f:
        f.write(f"[ {title} ]\n")
        
        # Write 15 indices per line (GROMACS convention)
        for i in range(0, len(indices_1indexed), 15):
            line_indices = indices_1indexed[i:i+15]
            f.write(" ".join(f"{idx:6d}" for idx in line_indices))
            f.write("\n")
    
    print(f"Wrote {len(indices)} indices to {filepath}")
